### ISSUE TITLE
[OFSettings] extend features

### ISSUE THREAD

**Issue by GunGraveKoga** [Midar/objfw#48] opened 2017-05-12 10:51 UTC
For now class OFSettings serach  ini-file with settings only in user config path setted in OS environment variable, and only named like application name passed to init method , this behavior is very limited.
Maybe OFSettings should have method, which sets list of folders to search config-file, similar to OFLocalization class method "addLanguageDirectory:"?
And, maybe, method "initWithApplicationName:" should be renamed to "initWithName:", it has more sense, different ini-files for different application setting...?

**Comment by Midar** [comment] 2017-05-13 11:39
The idea is that OFSettings is for storing all your settings for an application, and you do not need to care about the backend. In the future, this might write to the registry on Windows, to PLISTs on macOS, etc. If you want to store configs at certain paths (which it sounds you want), you should use OFINIFile directly - currently the only backend for OFSettings.

**Comment by Midar** [comment] 2017-06-21 20:22
Closing and marking it as invalid, as this is by design. Please reopen if OFINIFile does not satisfy your requirements!

**Closed by Midar** 2017-06-21 20:22 UTC
Labels: feature-request
