### ISSUE TITLE
Linux Subsystem for windows vs mingw

### ISSUE THREAD

**Issue by yobson** [Midar/objfw#52] opened 2017-08-19 11:53 UTC
Hello - This is both an issue and a fix but I can't work out the protocol about submitting code to another repository

Clang is broken on msys2, something to do with saving the libraries as lib{}.dll instead of {}.dll
So I have written a shell script that builds eveything with the Linux subsystem for windows.
1. You must have the windows 10 creators update (It means the Linux Ubuntu version is 16.04 instead of 14.04)
2. you must install the Linux subsystem or reinstall if you had it before the creators update and make sure you install the Ubuntu option (default and only option as of writing)
3. you open powershell and type ```bash``` to get to the Linux subsystem to run the script (for reasons I don't know, objfw fails the tests if it isn't inside powershell first?)

once in bash within powershell, this is the script you run as sudo:
```bash
green=`tput setaf 2`
reset=`tput sgr0`
echo "${green}Adding LLVM to sources${reset}"
llvmText="deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial main
deb-src http://apt.llvm.org/xenial/ llvm-toolchain-xenial main
# 4.0
deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-4.0 main
deb-src http://apt.llvm.org/xenial/ llvm-toolchain-xenial-4.0 main
# 5.0
deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-5.0 main
deb-src http://apt.llvm.org/xenial/ llvm-toolchain-xenial-5.0 main
"

if [ -e /etc/apt/sources.list.d/llvm.list ]
then
    echo "${green}Skipping LLVM Source installation - already there!${reset}"
else
    llvmText > /etc/apt/sources.list.d/llvm.list
    wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key| apt-key add -
fi

echo "${green}Updating & Upgrading Sources${reset}"
apt-get update
apt-get -y upgrade
apt-get install -y build-essential cmake autoconf clang-4.0 mingw-w64 gobjc++-mingw-w64 gobjc-mingw-w64
ls -s /usr/bin/clang-4.0 /usr/bin/clang
ls -s /usr/bin/clang++-4.0 /usr/bin/clang++

echo "${green}Getting wclang${reset}"
git clone https://github.com/tpoechtrager/wclang
cd wclang
echo "${green}Building wclang${reset}"
cmake -DCMAKE_INSTALL_PREFIX=/usr .
make
echo "${green}Copying Binaries to /usr/bin${reset}"
cd src
cp wclang /usr/bin/x86_64-w64-mingw32-clang
cp wclang /usr/bin/x86_64-w64-mingw32-clang++
cd ../../

echo "${green}Getting OBJFW${reset}"
git clone https://github.com/Midar/objfw
cd objfw
echo "${green}Running Config${reset}"
autoreconf
./configure --host=x86_64-w64-mingw32 --enable-static --disable-shared
echo "${green}Building${reset}"
make -j16
make install
echo "${green}Finished${reset}"
```
Here it is in gist: https://gist.github.com/yobson/3f6de8e375f45e1a4aeede1dbc2a37d1
hope this helps. Linux subsystem makes windows development 100000x better as it is far more intergrated with windows than msys2

hope my shell script helps!

James

**Comment by Midar** [comment] 2017-08-19 22:55
I cannot reproduce this. Did you set up msys2 by following the instructions in README-WINDOWS.md?

**Comment by yobson** [comment] 2017-08-20 10:56
Yes. I'll try again for you

**Comment by Midar** [comment] 2017-12-27 02:54
Closing due to lack of information. Please reopen if necessary.

**Closed by Midar** 2017-12-27 02:54 UTC
